require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'db/migrate/**/*'
    - 'db/seeds/**/*'
    - 'db/schema.rb'
    - 'config/**/*'
    - 'bin/**/*'
Style/AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Naming/PredicateName:
  Enabled: false
Style/ClassVars:
  Enabled: false
RSpec/ContextWording:
  Enabled: false
RSpec/MultipleExpectations:
  Max: 10